Update T1518.yaml (#621)
Seems like there is an extra tab here which is cause my yaml parser to break. 
```
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 3, column 33:
    display_name: Software Discovery
```